### ISSUE TITLE
No need to wait after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [MajicDesigns/MD_DS3231#3]
The line "`while (!Wire.available()) ; // wait`" after the Wire.requestFrom() in the file "MD_DS3231/src/MD_DS3231.cpp" may be removed. There is nothing to wait for.

When the Wire.requestFrom() returns, the I2C transaction has completely finished and the received data is waiting in a buffer in the Wire library.

**Comment by Keratox** [comment]
Logical not is only applied to the left hand side of comparison.  Comparison of constant with Boolean expression is always false.
line 389 is :  if (!writeDevice(ADDR_ALM1, bufRTC, 4) == 4)
line 389 s/b:  if (!(writeDevice(ADDR_ALM1, bufRTC, 4) == 4))
line 397 is :  if (!writeDevice(ADDR_ALM2, &bufRTC[1], 3) == 3)
line 397 s/b:  if (!(writeDevice(ADDR_ALM2, &bufRTC[1], 3) == 3))
