### ISSUE TITLE
Issues with SAMD-boards

### ISSUE THREAD

**Issue by SimGas** [MajicDesigns/MD_DS3231#4]
Hi discovered an issue with SAMD boards as they use the term RTC for their internal RTC. Solution could be to replace RTC with for example RTC_DS3231

**Comment by MajicDesigns** [comment]
Why do you need a separate RTC if there is already an internal one?

**Comment by SimGas** [comment]
The M0-Arduinos have a Internal RTC, but there is no possibility to attach a backup battery for time keeping when unpowered. Also, I just like the alarm functions and the precision of the DS3231 clock.

**Comment by MajicDesigns** [comment]
Short term you can edit the MD_DS3231.h file and change the name in there (at the bottom of the file). Longer term I will try and find a solution.

**Comment by SimGas** [comment]
Yes, I did that. The code compiles fine then. Unfortunately my board goes to sleep mode(at least it detaches  USB) immediately after uploading the example code MD_DS3231_test. But never mind. I've already found another library that works fine for me without the need to change my program code, becaused it's based on RTClib

Thank you very much for your fast replies!
