### ISSUE TITLE
Display of DOW

### ISSUE THREAD

**Issue by bioyavuz** [MajicDesigns/MD_DS3231#5]
Hi,
Thanks for this perfect library. This is the best among the libraries I examined. All the capabilities of DS3231 is  included. Examples are very easy with your detailed explanations.

The line 216 of example "MD_DS3231_Test" , in the function "printTime()":
PRINT("", dow2String(RTC.dow)); needs to be changed as:
PRINT("", dow2String(RTC.dow + 1));

Thank you again,
Yavuz Darendelioğlu

**Comment by MajicDesigns** [comment]
Fixed v1.2.2
